version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: workspace_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_INITDB_DATABASE: workspace_db
    volumes:
      - mongo_data:/data/db

  backend:
    build: 
      context: ./backend
    container_name: workspace_backend
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8080:80080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:adminpass@mongo:27017/workspace_db?authSource=admin
      JWT_SECRET: JasmineSecretKey
      JWT_EXPIRATION_MS: 86400000
      